---
title: "Chap 1 - Land Cover Graphs"
author: "Nguyen Tien Anh Quach"
date: "`r format(Sys.Date())`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=15, fig.height=8)
```

```{css, echo=FALSE}
h1, h4 {
  text-align: center;
  color: black;
  font-weight: bold;
}

/* Whole document: */
body{
  font-family: Times New Roman;
  font-size: 16pt;
}
/* Headers */
h1,h2,h3,h4,h5,h6{
  font-size: 24pt;
}

<style type="text/css">
body, td {
   font-size: 16px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 16px
}
</style>
  
```

# Introduction

These are codes to make land cover graphs for my first chapter (Red Run from 1987 to 2009).

## Load data

```{r message=F, warning=F}
library(readxl)
luc_8719 <- read_excel("F:/Thesis stuff/Data/Land cover data/Land Cover data.xlsx", 
                       sheet = "Percent dev line")

percent_impv <- read_excel("F:/Thesis stuff/Data/Land cover data/Land Cover data.xlsx", 
                             sheet = "Percent impv")
```

## Make the graph using ggplot

### Developed land

```{r message=F, warning=F}
library(ggplot2)
library(dplyr)

luc_8719$`Sub-watershed` = factor(luc_8719$`Sub-watershed`,levels=c("B9", "B7","B9A","B1"))


chap1_devland <- luc_8719 %>% filter(Year < 2009) %>% 
  filter(!is.na(`Sub-watershed`)) %>% ggplot(aes(x=Year, y=Percent,shape=`Sub-watershed`)) +
  geom_point(aes(shape=`Sub-watershed`),size=6, fill="gray") +
  scale_shape_manual(values=c(21,22,23,24)) +
  labs(
    caption = "Source: USGS") +
  theme(
    plot.title = element_text(color = "#0099f9", size = 20, face = "bold", hjust = 0.5),
    plot.caption = element_text(face = "italic", hjust = 0, size =15),
    panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2),
    legend.key=element_blank()) +
  scale_x_continuous(breaks = seq(1987, 2009, by = 3)) + 
  scale_y_continuous(breaks = seq(0, 60, by=5))+
  labs(
    x = "Year",
    y = "Developed land (%)") +
  theme(
    axis.title.x = element_text(color = "black", size = 20, face = "bold"),
    axis.title.y = element_text(color = "black", size = 20, face = "italic")) +
  theme(legend.position="right")+
  theme(legend.title = element_text(color = "Black", size = 14),
        legend.text = element_text(color = "black")) + 
  theme(axis.title.x = element_text(margin=margin(t=10)), #add margin to x-axis title
        axis.title.y = element_text(margin=margin(r=20)),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15)) + 
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=15), #change legend title font size
        legend.text = element_text(size=15)) #change legend text font size

chap1_devland

ggsave("Chapter 1 Developed land.jpeg",chap1_devland,width=15,height=8)
```

### ISA

```{r message=F, warning=F}
library(ggplot2)
library(dplyr)

percent_impv$`Sub-watershed` = factor(percent_impv$`Sub-watershed`,levels=c("B9", "B7","B9A","B1"))
  
chap1_isa <- percent_impv %>% filter(Year < 2009) %>%
   ggplot(aes(x=as.factor(Year), y=`Percent impv`, shape=`Sub-watershed`)) +
      geom_point(aes(shape=`Sub-watershed`),size=6,fill="gray") +
      scale_shape_manual(values=c(21,22,23,24)) +
      annotate("text",x=2.5,y=5,label="ISA threshold for brook trout existence (Stranko et al. 2008)", size = 6,fontface="italic") +
      geom_hline(yintercept=4, linetype="dashed", 
                 color = "red", size=1.5) +
      labs(
        caption = "Source: NLCD") +
      theme_bw() +
      theme(axis.line = element_line(color='black'),
            plot.background = element_blank(),
            panel.grid.minor = element_blank(),
            panel.grid.major = element_blank()) +
      theme(
        plot.title = element_text(color = "#0099f9", size = 30, face = "bold", hjust = 0.5),
        plot.caption = element_text(face = "italic", size=15, hjust = 0)) +
      scale_x_discrete() +
      scale_y_continuous(breaks = seq(0, 30, by=2))+
      labs(
        x = "Year",
        y = "ISA (%)") +
      theme(
    axis.title.x = element_text(color = "black", size = 20, face = "bold"),
    axis.title.y = element_text(color = "black", size = 20, face = "italic")) +
  theme(legend.position="right")+
  theme(legend.title = element_text(color = "Black", size = 14),
        legend.text = element_text(color = "black")) + 
  theme(axis.title.x = element_text(margin=margin(t=10)), #add margin to x-axis title
        axis.title.y = element_text(margin=margin(r=20)),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15)) + 
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=15), #change legend title font size
        legend.text = element_text(size=15)) #change legend text font size

chap1_isa
ggsave("Chapter 1 ISA.jpeg",chap1_isa,width=15,height=8, bg="white")

```

